### ISSUE TITLE
被豆瓣封IP

### ISSUE THREAD

**Issue by bei2love** [Libitum/jellyfin-plugin-douban#12]
使用最新的release版本安装后，现在出现了打开豆瓣网站进行搜索后提示“检测到有异常请求从你的 IP 发出，请 登录 使用豆瓣。”

插件有登录功能或防IP被屏蔽的方法吗

**Comment by bwskyer** [comment]
你一次性不要刮削太多，这是正常情况，如果在某些时段一次性出现大量的API访问IP就会被封，隔天就正常，所以不建议一次性刮削太多电影
