### ISSUE TITLE
您好，可否提供一下电影和剧集的 命名规范（更有助于豆瓣抓取信息）

### ISSUE THREAD

**Issue by ghost** [Libitum/jellyfin-plugin-douban#14]
尊敬的作者：
  您好，非常感谢您的精品项目。特别实用！
  但是发现由于影片资源和电视剧资源命名规范问题，不能更好的抓取到豆瓣的信息。能否提供一下命名规范建议。
   比如电影《本杰明·巴顿奇事》，在豆瓣上的全部标题是 本杰明·巴顿奇事 The Curious Case of Benjamin Button (2008) ，那么我在本地的资源文件，应该怎样命名更有利于项目抓取影片信息？

**Comment by Libitum** [comment]
Hi，因为豆瓣 api 的 search 已经关闭了，而网站的 search 页面只提供关键词搜索，不能添加类似年份、类型等信息，所以命名规范上并没有特别要求，通常会提取年份之前的所有内容，作为关键词提交给豆瓣进行搜索。当然，这也涉及排序问题。目前是以豆瓣搜索页的第一条结果作为默认结果的。
所以，理论上只要电影的命名符合豆瓣关键词第一排序，即可以准确找到相关信息。

关于电视剧的命名规范，请参考 https://jellyfin.org/docs/general/server/media/shows.html。

我最近也在考虑有没有其他类似服务可以替代，毕竟现在豆瓣越来越封闭了。
如果您有什么建议或者想法，也欢迎提出 ;-)
