### ISSUE TITLE
想问一下开发流程

### ISSUE THREAD

**Issue by HaitianLiu** [Libitum/jellyfin-plugin-douban#17]
最近想自己做个获取字幕的 plugin，对 .net 开发不是很熟悉，想问一下 plugin 的开发怎么设置断点 debug。
没有找到其他联系方式，只能借助issue提问，请见谅~

**Comment by Libitum** [comment]
我也有兴趣做字幕的 plugin，感觉可以一起合作？我对 .net 也不是很熟:-) 摸索着来的
感觉可以一起学习？
关于 plugin 的 debug，我是通过 mock 写单测进行的，因为在整个 jellyfin 中测试 plugin 会非常麻烦。我的代码中有一些 mock 的地方，可以参考。这时候断点就和常规的做法一样了

**Comment by HaitianLiu** [comment]
感谢回复。我还没实际开发过，只是大致过了一下几个 plugin 的代码，可以 email 下联系方式，后面再交流一下。
我的 email：wantedliu@gmail.com
