### ISSUE TITLE
在爬去某些电影的时候数据不是很全。

### ISSUE THREAD

**Issue by a13087635768** [Libitum/jellyfin-plugin-douban#2]
![360截图20191028221406699](https://user-images.githubusercontent.com/23163284/67685952-e6128d00-f9d0-11e9-821f-b5d09dfccf74.jpg)
### 这个是使用你这个插件爬取的 没有找到电影的简介其他的倒是无所谓

![360截图20191028221427428](https://user-images.githubusercontent.com/23163284/67686014-fe82a780-f9d0-11e9-9ed0-290a8afd76a2.jpg)
### 以后会支持电视剧模块吗？

**Comment by Libitum** [comment]
@a13087635768 抱歉前一段时间比较忙所以回复晚了，这个 bug 已经修复了，请使用 v0.2 版本重试一下，谢谢！
关于电视剧模块，由于 douban 的信息不充分，所以只能识别 Series + Season，不能分开 Series 和 Season，并且缺失每一集的信息。我还在想办法看怎么解决。
最后，谢谢试用！
