### ISSUE TITLE
Jellyfin 10.6.0 Repository URL

### ISSUE THREAD

**Issue by JerryBian** [Libitum/jellyfin-plugin-douban#20]
好像最新版本的 Jellyfin 安装插件需要提供一个 URL 地址，请问该插件怎么填呢？

![Screen Shot 2020-07-20 at 9 43 29 PM](https://user-images.githubusercontent.com/1439095/87944609-34713a00-cad2-11ea-8246-28d41c218dcf.png)

**Comment by Libitum** [comment]
@JerryBian Hi 您好，这是 10.6.0 新增的功能，我也在和 Jellyfin 官方的开发者沟通，正在适配，请稍等哈

**Comment by Libitum** [comment]
@JerryBian 可以填 https://raw.githubusercontent.com/Libitum/jellyfin-plugin-douban/master/manifest.json
也请帮忙测试一下，谢谢！

**Comment by JerryBian** [comment]
@Libitum 👍，可以工作。

**Comment by JerryBian** [comment]
顺便，我能咨询一下几个疑问吗？

1. 如果我有多个 metadata provider，他们是按照顺序一个个来查找，如果 Douban 已经找到了，接下来的是直接算成功了，还是得必须按顺序找下一个 Provider？按照我的实验，log 中 Douban 已经找到了，但是下一个 Provider 失败了，然后导致 metadata refresh 都失败了。不知道这里面究竟是什么逻辑？

2. 究竟应该如何命名电影和电视剧呢？Douban 这个插件是怎么解析文件名的呢？是根据什么断句的么，然后主标题、副标题以及英文名称有什么优先级吗？

比如，我有这样一个电影：`The.Bourne.Supremacy.谍影重重2.至尊伯恩.双语字幕.mkv`

可能是 off-topic 了，但是如果能帮我解答一下就不胜感激了 :-)

**Comment by Libitum** [comment]
> 
>     1. 如果我有多个 metadata provider，他们是按照顺序一个个来查找，如果 Douban 已经找到了，接下来的是直接算成功了，还是得必须按顺序找下一个 Provider？按照我的实验，log 中 Douban 已经找到了，但是下一个 Provider 失败了，然后导致 metadata refresh 都失败了。不知道这里面究竟是什么逻辑？
> 
>

是按照配置里得顺序进行的，并且图片、元数据在配置里都是分开配置的。如果有一个已经找到了，则不会再使用下一个 Provider。我猜你是不是没有打开高级设置，把图片等项目里的 douban 打开？

>
>     2. 究竟应该如何命名电影和电视剧呢？Douban 这个插件是怎么解析文件名的呢？是根据什么断句的么，然后主标题、副标题以及英文名称有什么优先级吗？
> 
> 
> 比如，我有这样一个电影：`The.Bourne.Supremacy.谍影重重2.至尊伯恩.双语字幕.mkv`
> 

目前使用的是 Jellyfin 官方建议的方法从文件名中提取，默认只尝试解析年份，其他的应该是当作一个整体的（电视剧会把剧集、session 等单独提取出来）。以你的电影为例，文件名中没有明显的特征，所以会用整个 “The.Bourne.Supremacy.谍影重重2.至尊伯恩.双语字幕” 进行搜索。不过好在豆瓣本身的搜索比较 nb，即使文件名这么长，依然可以准确的找出 “谍影重重2”。

另外，对于某些无法正确识别的电影，也可以用 Jellyfin 中的 “识别” 功能，输入电影名称，可以直接搜索。同时，这个界面下页支持直接填写豆瓣的 id。

关于文件名确实没有什么很好的策略，我遇到的 case 也比较少。如果有无法自动识别的 case，欢迎发出来大家一起看一下哈。

**Comment by JerryBian** [comment]
感谢感谢~~~
