### ISSUE TITLE
插件很好用，谢谢大佬

### ISSUE THREAD

**Issue by yyf127** [Libitum/jellyfin-plugin-douban#24]
jellyfin用豆瓣，搜刮效率确实比TMDb块很多，但是有些电影识别还是出不来，手动识别电影也会出现识别不出来，这个是豆瓣原因还是其他原因吗？

**Comment by Libitum** [comment]
> 
> 
> jellyfin用豆瓣，搜刮效率确实比TMDb块很多，但是有些电影识别还是出不来，手动识别电影也会出现识别不出来，这个是豆瓣原因还是其他原因吗？

请问可以提供一下识别不出来的电影的文件名么？谢谢！

**Comment by yyf127** [comment]
> > jellyfin用豆瓣，搜刮效率确实比TMDb块很多，但是有些电影识别还是出不来，手动识别电影也会出现识别不出来，这个是豆瓣原因还是其他原因吗？
> 
> 请问可以提供一下识别不出来的电影的文件名么？谢谢！

无敌浩克、美国队长，这两个，还有其他的一些也有，像无敌浩克手动识别不出来，但是可以拆开通过搜索无敌，搜索出无敌浩克，美国队长直接都不出来，队长可以搜出来。还有顺便问一下你这个插件可以转发不

**Comment by Libitum** [comment]
> 无敌浩克、美国队长，这两个，还有其他的一些也有，像无敌浩克手动识别不出来，但是可以拆开通过搜索无敌，搜索出无敌浩克，美国队长直接都不出来，队长可以搜出来。

可以麻烦提供一下原始的文件名么？这样我可以确认下是否是文件名抓取机制上的问题哈~

> 还有顺便问一下你这个插件可以转发不
请问这个是指什么转发？

**Comment by yyf127** [comment]
> > 无敌浩克、美国队长，这两个，还有其他的一些也有，像无敌浩克手动识别不出来，但是可以拆开通过搜索无敌，搜索出无敌浩克，美国队长直接都不出来，队长可以搜出来。
> 
> 可以麻烦提供一下原始的文件名么？这样我可以确认下是否是文件名抓取机制上的问题哈~
> 
> > 还有顺便问一下你这个插件可以转发不
> 
> 请问这个是指什么转发？

转发到其他论坛，当然我会附上你的项目源地址

**Comment by yyf127** [comment]
> > 无敌浩克、美国队长，这两个，还有其他的一些也有，像无敌浩克手动识别不出来，但是可以拆开通过搜索无敌，搜索出无敌浩克，美国队长直接都不出来，队长可以搜出来。
> 
> 可以麻烦提供一下原始的文件名么？这样我可以确认下是否是文件名抓取机制上的问题哈~
 路径/media/漫威电影/无敌浩克.国英双语双字.mkv
路径/media/漫威电影/美国队长/美国队长 Captain America The First Avenger HD MP4 2011 美国 动作 科幻 冒险 中文字幕.mp4

**Comment by Libitum** [comment]
> 转发到其他论坛，当然我会附上你的项目源地址

当然，这个项目是 MIT 协议，可以任意转发、二次开发、拿去盈利，都没有问题。也欢迎帮忙推广 :-)

关于文件名，我稍后测试一下哈

**Comment by yyf127** [comment]
> > 转发到其他论坛，当然我会附上你的项目源地址
> 
> 当然，这个项目是 MIT 协议，可以任意转发、二次开发、拿去盈利，都没有问题。也欢迎帮忙推广 :-)
> 
> 关于文件名，我稍后测试一下哈

好的，谢谢

**Comment by Libitum** [comment]
> 
> > 路径/media/漫威电影/无敌浩克.国英双语双字.mkv
> > 路径/media/漫威电影/美国队长/美国队长 Captain America The First Avenger HD MP4 2011 美国 动作 科幻 冒险 中文字幕.mp4

我测试了一下，“无敌浩克.国英双语双字.mkv” 中没有明确的区分信息，所以会用整个字符串去搜索，在豆瓣上确实无法找到。
不过用 “识别” 功能有问题，是有两个原因：

**Comment by Libitum** [comment]
@yyf127 Hi 您好，能否帮忙测试一下 1.0.1 版本有没有解决你的问题？应该有所改善。谢谢！

**Comment by yyf127** [comment]
> @yyf127 Hi 您好，能否帮忙测试一下 1.0.1 版本有没有解决你的问题？应该有所改善。谢谢！

测试了，识别都没问题了，已经不会出现以前那种识别不到的情况了 ，非常感谢

**Comment by Libitum** [comment]
> 测试了，识别都没问题了，已经不会出现以前那种识别不到的情况了 ，非常感谢

谢谢！
