### ISSUE TITLE
目前是还未支持jellyfin的手动识别功能么？

### ISSUE THREAD

**Issue by freedom0622** [Libitum/jellyfin-plugin-douban#25]
在影片详情页右上"..."处选择识别，输入影片名称，会秒返回无结果(除douban刮削外未使用其他刮削器)

未观察到有douban相关api请求，jellyfin的"Items/RemoteSearch/Movie"接口response为"[]"

**Comment by Libitum** [comment]
@freedom0622 
这个功能是支持的，也支持直接输入 douban id。但是为了防止被 douban 封 ip，所以默认会间隔 3-5 秒才会发出请求。
这里失败的原因，也有可能是因为后台在刷新数据，导致手动识别被 delay 了。
我来看一下是不是这个原因。
另外在手动识别的时候，感觉并不会请求很频繁，所以似乎也不需要间隔。

**Comment by Libitum** [comment]
@freedom0622 是 Jellyfin 10.6.x 引入的一个问题，识别的时候 lauguage 不生效导致的。我在想我我绕过去还是提 pr 给官方修....

**Comment by freedom0622** [comment]
> @freedom0622 是 Jellyfin 10.6.x 引入的一个问题，识别的时候 lauguage 不生效导致的。我在想我我绕过去还是提 pr 给官方修....

收到，谢谢大佬

**Comment by Libitum** [comment]
@freedom0622 Hi 请问能否帮忙测试一下 1.0.1 版本是否解决了你的问题？谢谢！

**Comment by freedom0622** [comment]
> @freedom0622 Hi 请问能否帮忙测试一下 1.0.1 版本是否解决了你的问题？谢谢！

已确认修复~

**Comment by freedom0622** [comment]
> @freedom0622 Hi 请问能否帮忙测试一下 1.0.1 版本是否解决了你的问题？谢谢！

已确认修复~
