### ISSUE TITLE
0.2版本-刮削的时候会默认为其他数据源，不准确，手动可选

### ISSUE THREAD

**Issue by s1oz** [Libitum/jellyfin-plugin-douban#3]
![TIM截图20191116130853](https://user-images.githubusercontent.com/32033912/68988429-45e2b200-0872-11ea-90e8-42c5884b054f.jpg)
![TIM截图20191116130838](https://user-images.githubusercontent.com/32033912/68988430-45e2b200-0872-11ea-982e-b662afd394e5.jpg)
![TIM截图20191116130826](https://user-images.githubusercontent.com/32033912/68988431-45e2b200-0872-11ea-8879-a122c1151d2b.jpg)

**Comment by Libitum** [comment]
请问您是否在媒体配置的里面打开这个 Provider，并且设置优先级更高一些了呢？

**Comment by Libitum** [comment]
@s1oz 您好，请问可以把您的操作过程和问题再描述一下么？谢谢！

**Comment by s1oz** [comment]
> @s1oz 您好，请问可以把您的操作过程和问题再描述一下么？谢谢！
> 这里手动搜索应该是可以的，您指的『默认为其他数据源』，是指自动刮削的时候没有使用 douban 的么？请问是否在媒体库的配置里打开 Douban 的 Provider 并且设置为较高的优先级呢？
> 谢谢！

默认tmdb源，正确识别影片
安装0.2版本后重启，该媒体库设置为单独douban刮削
媒体库点击刷新元数据（覆盖所有元数据-不替换图片）
然后正确的这个片子就自动识别为哆啦A梦
点击影片识别，输入正确片名（富美子之足）
出现此图
![68988429-45e2b200-0872-11ea-90e8-42c5884b054f](https://user-images.githubusercontent.com/32033912/69029807-f2f33100-0a10-11ea-8ef1-3bf113b7420d.jpg)

**Comment by Libitum** [comment]
@s1oz 请问可否提供下这个电影的原始文件名？我可以在本地做一些测试，谢谢！

**Comment by s1oz** [comment]
@Libitum 富美子之足

**Comment by Libitum** [comment]
@s1oz 我发现应该是 douban 搜索的排序问题。从你的截图也可以看到，哆啦A梦是排在第一位的。因为 douban 目前不支持更多约束条件的搜索，比如发行年份等等。所以默认会自动挑选搜索结果的第一个作为默认结果。
不过我这边复现的时候，使用 https://www.douban.com/search?cat=1002&q=%E5%AF%8C%E7%BE%8E%E5%AD%90%E4%B9%8B%E8%B6%B3  来看，正确的结果已经排在第一位了，所以我这边的结果是正确的，很奇怪。
TMDB 是支持按年份 search 的，所以结果会更准一些。我再研究下看有没有其他更好的方法哈。

**Comment by s1oz** [comment]
@Libitum 感觉开发调试，谢谢 期待插件成熟支持剧集

**Comment by Libitum** [comment]
Support search metadata by Douban ID and media name from v0.3.0. So just close this issue now. Thanks for support!
