### ISSUE TITLE
还没有能继续用吗？

### ISSUE THREAD

**Issue by 425369918** [Libitum/jellyfin-plugin-douban#36]
等了好久了，支持大佬得

**Comment by Libitum** [comment]
@425369918 我这两天在测试！争取年前 release 出来！

**Comment by MAOA-L** [comment]
刚把爹

**Comment by wzdxy** [comment]
加油，刚装了10.7 没有豆瓣刮削很难受😂

**Comment by Libitum** [comment]
> 加油，刚装了10.7 没有豆瓣刮削很难受😂

大家都这么激进的么 😂   10.7还没发布，兼容一下倒是问题不大

**Comment by 425369918** [comment]
有没有emby可以用的插件啊

**Comment by Libitum** [comment]
> 有没有emby可以用的插件啊

稍安，我们先解决插件能用的问题。最近豆瓣封的比较猛。

**Comment by Libitum** [comment]
@wzdxy 10.7 已经支持，请试用一下最新的 2.0.0-rc1 版本。
