### ISSUE TITLE
10.7.0插件不支持，作者大大抽空更新下哦

### ISSUE THREAD

**Issue by Toretto5060** [Libitum/jellyfin-plugin-douban#37]
10.7.0插件不支持，作者大大抽空更新下哦 @Libitum

**Comment by Libitum** [comment]
我试了一下，豆瓣现在的反爬策略有点猛，各种直接封禁，有点头大

**Comment by Libitum** [comment]
@Toretto5060 我看了下 10.7.0 是还没正式发布，请问您用的测试版么？

**Comment by gldl137** [comment]
10.7是测试版，更新很大，能支持最好了

**Comment by 425369918** [comment]
> @ Toretto5060我看了下10.7.0是还没正式发布，请问您用的测试版么？

emby可以用这个插件嘛

**Comment by Libitum** [comment]
@Toretto5060 @gldl137  master 已经支持 10.7.0 了，我明天再测试一下，如果没问题就发个 rc 版本出来

**Comment by gldl137** [comment]
NB，👍

**Comment by Eadger** [comment]
为什么我这里并没有显示有 10.7.0 这个版本呢？
![image](https://user-images.githubusercontent.com/45703375/108579580-bfbdf100-737b-11eb-8ccb-33a889718253.png)

**Comment by Libitum** [comment]
> 为什么我这里并没有显示有 10.7.0 这个版本呢？
> ![image](https://user-images.githubusercontent.com/45703375/108579580-bfbdf100-737b-11eb-8ccb-33a889718253.png)

稍等，我今天测试一下，没问题再发布

**Comment by Eadger** [comment]
> > 为什么我这里并没有显示有 10.7.0 这个版本呢？
> > ![image](https://user-images.githubusercontent.com/45703375/108579580-bfbdf100-737b-11eb-8ccb-33a889718253.png)
> 
> 稍等，我今天测试一下，没问题再发布

感谢大大

**Comment by Libitum** [comment]
@Eadger 麻烦再试一下呢？

**Comment by Eadger** [comment]
> @Eadger 麻烦再试一下呢？

不行，我这里在无线转圈圈
![image](https://user-images.githubusercontent.com/45703375/108622666-701c1a00-748e-11eb-8bef-cf262252e307.png)

**Comment by Libitum** [comment]
@Eadger 查到 repo 文件有个 error，已经 fix 了，可以再试一下。请注意，2.0.0 只支持 Jellyfin 10.7.0-rcX 的版本哈，10.6.x 不支持。

**Comment by Toretto5060** [comment]
啊啊啊，对的对的。。。测试版目前可以倍速，这点是比较喜欢的，等正式版也没关系，哈哈哈，感谢您的奉贤

发送自 Windows 10 版邮件应用

发件人: Libitum
发送时间: 2021年2月5日 下午 3:22
收件人: Libitum/jellyfin-plugin-douban
抄送: Toretto; Mention
主题: Re: [Libitum/jellyfin-plugin-douban] 10.7.0插件不支持，作者大大抽空更新下哦 (#37)

@Toretto5060 我看了下 10.7.0 是还没正式发布，请问您用的测试版么？

**Comment by Libitum** [comment]
@Toretto5060 v2.0.0-rc1 已经支持 Jellyfin 10.7.0-rc3，可以试一下哈
