### ISSUE TITLE
Docker 安装的jellyfin 如何使用这个插件呢

### ISSUE THREAD

**Issue by yfdoor** [Libitum/jellyfin-plugin-douban#4]
如题

**Comment by Libitum** [comment]
@yfdoor 抱歉回复晚了。docker 安装的话需要配置一个 /config 的路径，把下载后的文件解压到 /config 对应的目录里的 ./plugins/ 下即可。
比如，我自己电脑上 /config 对应的是 /home/abc/jellyfin/config，那么解压到 /home/abc/jellyfin/config/plugins 下即可。
如有问题请与我联系。谢谢！
