### ISSUE TITLE
似乎只能识别电影源，电视节目无法使用

### ISSUE THREAD

**Issue by zuosc** [Libitum/jellyfin-plugin-douban#5]
![image](https://user-images.githubusercontent.com/8411781/70905970-39ec3a80-2040-11ea-8be6-c395004a186d.png)
![image](https://user-images.githubusercontent.com/8411781/70905979-42dd0c00-2040-11ea-8b04-71c0a7025215.png)

**Comment by Libitum** [comment]
@zuosc 您好！目前还没找到一个比较好的方法支持电视节目，主要原因在于豆瓣的 TV 组织形式和 Jellyfin 默认的数据组织形式不太一样，我还在尝试看有没有方法可以支持。多谢试用！

**Comment by Libitum** [comment]
从 v0.3.0 开始支持电视剧，谢谢！
Support TV series from v0.3.0. Thanks!
