### ISSUE TITLE
Windows 平台安装问题

### ISSUE THREAD

**Issue by April-BOY** [Libitum/jellyfin-plugin-douban#8]
请问Windows平台下怎么安装这个插件？我在Windows平台下安装了jellyfin的安装版和绿色版，都没有找到plugins文件夹，在jellyfin打开的网页端的【插件】那里也没找到安装的方式

**Comment by Libitum** [comment]
@April-BOY 抱歉我这会儿没有 windows 环境，jellyfin 的 dashboard 首页下面会显示当前的一些路径，比如 log 路径、metadata 路径等，能方便帮忙截一下图么？
另外，我在和官方联系，看能否加入到官方的插件库里

**Comment by April-BOY** [comment]
![image](https://user-images.githubusercontent.com/19245482/75457792-de331b80-59b7-11ea-837b-e54b42b9488c.png)
这应该是你需要的，如果不是，我还可以帮忙截图。

另外，我想跟你讨论两个问题：
（1）我使用 kodi 刮削本地的媒体资源，刮削器使用【Local information only】模式，使用 tinymediamanager 和”emby的豆瓣刮削器“刮削只生成了nfo文件（没有刮削其他的信息），kodi都没法识别出来。但是，使用emby默认的刮削器：thetvdb，themoviedb等生成的nfo文件就没有问题都可以显示（就是网络偶尔不稳定显示不全，毕竟需要科学上网，所以，我迫切的希望你的这个插件能尽快开发好，并且能最大化地媲美thetvdb，themoviedb等插件的体验），我比较了他们的区别，发现nfo的xml结构是不同的，我还没使用你的刮削器，希望能给你点建议或者在后期开发的时候可以测试下这个问题。
（2）就是生成刮削器生成的nfo文件的演员部分，我希望你能加入显示演员图片的链接（如果这个可以实现的话）。这样更贴合kodi的显示效果，查看媒体的信息时能有更好的体验，也算是强迫症吧。

”emby的豆瓣刮削器“生成的nfo文件是没有的，如下：
<actor>
    <name>Yuan Quan</name>
    <role>Kang Xiaoyu</role>
    <type>Actor</type>
  </actor>

emby 默认的刮削器和tinymediamanager这个软件都有，如下：
<actor>
    <name>Tae In-Ho</name>
    <role>Kim Young-ha</role>
    <thumb>http://thetvdb.com/banners/person/7991516/tv-372807.jpg</thumb>
    <profile/>
  </actor>

**Comment by Libitum** [comment]
Hi @April-BOY 多谢你的截图哈！从截图上看，plugins 目录应该在 C:\Users\${Name}\AppData\Local\jellyfin\plugins，如果没有的话可以手动创建一下。我也在联系官方看能否加到官方的 plugins 里了，后续可以直接下载。

关于你的两个问题：
（1）抱歉 emby 那边我不太了解，听你的意思大概率像是刮削器实现或者配置的问题。Jellyfin 这个刮削器我测试后倒是都能支持，不过需要配置使用 nfo 模式，并把图片都保存在同一目录下
（2）我这边是包含演员图片的 :-)

不过目前仍然有一些功能没有实现，比如大的 background 图片，等等。后续会持续完善，也希望大家多多提意见 :-)

**Comment by April-BOY** [comment]
![image](https://user-images.githubusercontent.com/19245482/75513426-cb5c2d80-5a2f-11ea-8d1a-bd4157a0da2a.png)
![image](https://user-images.githubusercontent.com/19245482/75513538-1b3af480-5a30-11ea-87f3-ac80684c9b6e.png)
![image](https://user-images.githubusercontent.com/19245482/75513638-61905380-5a30-11ea-80d1-ce84b711cbfd.png)
确实是在C:\Users${Name}\AppData\Local\jellyfin\plugins这个目录下，我安装了官方的 Anime 插件，就是在这个目录下找到的

不过，我下载你的插件解压到这个目录，jellyfin无法识别，将jellyfin-plugin-douban-0.3.0里的文件夹Jellyfin.Plugin.Douban整个提取出来重命名成Douban也不行。估计是要像官方的Anime一样编译成dll文件才行？

**Comment by Libitum** [comment]
Hi @April-BOY 请问你放在 Douban 目录里的是什么内容呢？
如果是从 Release 页面下载的 0.3.0 版本的 Jellyfin.Plugin.Douban.tar.gz，解压后直接就是一个 Douban 的文件夹，里面有 dll, json, pdb 三个文件，目录整个放进去就可以了。当然只有 dll 是必须的哈

**Comment by Libitum** [comment]
另外多谢你的帮助，我会在 Readme 里更新下 Windows 的配置方法，多谢！

**Comment by Libitum** [comment]
Hi @April-BOY  请问怎么样了？能否正常使用呢？

**Comment by April-BOY** [comment]
@Libitum 可以正常使用了，不过存在一个问题：
![image](https://user-images.githubusercontent.com/19245482/75639402-8c1a2080-5c6b-11ea-80f2-16ccc8fd6c49.png)
在win10的【所有应用】处启动jellyfin会不加载你这个插件，必须在jellyfin的安装目录下启动才可以加载插件
![image](https://user-images.githubusercontent.com/19245482/75639465-e74c1300-5c6b-11ea-9c98-c6586ff79c30.png)

**Comment by Libitum** [comment]
这么神奇！两种方式下，请问 jellyfin 的 dashboard 首页下显示的路径是一致的么？
我看了下 Jellyfin 的源码，就是在 plugins 目录下遍历所有 dll 的，所以感觉只能是路径不对？
Windows 不是 dotnet core 的主场么，怎么也会有这种奇葩的问题...

**Comment by April-BOY** [comment]
不一致，在【所有应用】处启动jellyfin时，看 jellyfin 的控制台窗口和 dashboard首页，cache、log等目录都加载的是我安装的在 D 盘的 jellyfin 的目录，估计是会随安装目录自动更改加载的目录，而且就算在我安装的目录新建一个 plugins 文件夹放插件，在控制台窗口里就不加载插件了，dashboard 首页当然就没有了

**Comment by Libitum** [comment]
明白，谢谢！

**Comment by YukiCoco** [comment]
在 administrator 用户下安装，插件保存在 `C:\ProgramData\Jellyfin\Server\plugins` 这个文件夹下

**Comment by Libitum** [comment]
@YukiCoco 谢谢！我随后更新到 README 中
